# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Urban_research
                                 A QGIS plugin
 Walkability (QGIS 3 & 4 compatible)
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-04-14
        copyright            : (C) 2026 by Student
        email                : a@a.a
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Urban_research class from file Walkability.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    from .Walkability import Urban_research
    return Urban_research(iface)
