# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Urban_research
                                 A QGIS plugin
 Walkability Analysis (QGIS 3 & 4 compatible)
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-01-01
        git sha              : $Format:%H$
        copyright            : (C) 2024
        email                : your@email.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os.path
import sys
import math
import heapq
import json
import time
import csv
import logging
from collections import defaultdict
from datetime import datetime

# ═══════════════════════════════════════════════════════
#  QGIS VERSION DETECTION & COMPATIBILITY LAYER
# ═══════════════════════════════════════════════════════

from qgis.core import Qgis

# Определяем версию QGIS
QGIS_VERSION_INT = Qgis.QGIS_VERSION_INT
IS_QGIS4 = QGIS_VERSION_INT >= 40000

# Условные импорты в зависимости от версии
if IS_QGIS4:
    # QGIS 4.x использует PyQt6
    from PyQt6.QtCore import QSettings, QTranslator, QCoreApplication, Qt
    from PyQt6.QtGui import QIcon, QAction  # В PyQt6 QAction перенесён в QtGui!
    from PyQt6.QtWidgets import QFileDialog, QMessageBox, QDialog
else:
    # QGIS 3.x использует PyQt5 через qgis.PyQt
    from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication, Qt, QVariant
    from qgis.PyQt.QtGui import QIcon
    from qgis.PyQt.QtWidgets import QAction, QFileDialog, QMessageBox, QDialog

# Импорты QGIS core
from qgis.core import (
    QgsProject, QgsVectorLayer, QgsFeature, QgsGeometry, QgsPointXY,
    QgsField, QgsFields, QgsWkbTypes, QgsCoordinateReferenceSystem,
    QgsCoordinateTransform, QgsSpatialIndex, QgsMessageLog,
    Qgis, QgsVectorFileWriter, QgsTask, QgsApplication
)

# Импорты QGIS GUI
try:
    from qgis.gui import QgsFileWidget
except ImportError:
    # Fallback если QgsFileWidget недоступен
    QgsFileWidget = None

# Импорт диалога
from .Walkability_dialog import Urban_researchDialog

# ═══════════════════════════════════════════════════════
#  COMPATIBILITY HELPERS
# ═══════════════════════════════════════════════════════

def get_qvariant_type(field_type):
    """Получить тип QVariant в зависимости от версии QGIS."""
    if IS_QGIS4:
        # В PyQt6/QGIS 4 используется QMetaType вместо QVariant
        from PyQt6.QtCore import QMetaType
        type_mapping = {
            'String': QMetaType.Type.QString,
            'Double': QMetaType.Type.Double,
            'Int': QMetaType.Type.Int,
        }
        return type_mapping.get(field_type, QMetaType.Type.QString)
    else:
        # В PyQt5/QGIS 3 используется QVariant
        type_mapping = {
            'String': QVariant.String,
            'Double': QVariant.Double,
            'Int': QVariant.Int,
        }
        return type_mapping.get(field_type, QVariant.String)

def check_null_value(value):
    """Проверка на NULL значение в зависимости от версии."""
    if value is None:
        return True
    
    if IS_QGIS4:
        # В PyQt6 QVariant может не использоваться, проверяем просто значение
        if isinstance(value, str) and not value.strip():
            return True
        return False
    else:
        # В PyQt5 проверяем через QVariant
        try:
            if isinstance(value, QVariant) and value.isNull():
                return True
        except:
            pass
        if isinstance(value, str) and not value.strip():
            return True
        return False

# ═══════════════════════════════════════════════════════
#  КОНСТАНТЫ
# ═══════════════════════════════════════════════════════

MIN_WEIGHT = 1e-6
POLYGON_BUFFER_M = 8.0
PARK_PROXIMITY_NEAR = 0.95
PARK_PROXIMITY_FAR = 1.0
DENSITY_THRESHOLD = 4000.0
WIDTH_SCALE = 10.0
EXPORT_CRS = "EPSG:4326"
ANALYSIS_CRS = "EPSG:3857"
COORD_PRECISION = 2

SURFACE_COEFFS = {
    "ground": 0.99,
    "asphalt": 0.97,
    "paving_stones": 0.95,
}

# Поддерживаемые форматы пространственных данных
SUPPORTED_FORMATS = {
    'gpkg': ('GeoPackage', True, ['*.gpkg']),
    'shp': ('Shapefile', False, ['*.shp']),
    'geojson': ('GeoJSON', False, ['*.geojson', '*.json']),
    'gml': ('GML', False, ['*.gml']),
    'kml': ('KML', False, ['*.kml']),
    'kmz': ('KMZ', False, ['*.kmz']),
    'tab': ('MapInfo TAB', False, ['*.tab']),
    'sqlite': ('SQLite', True, ['*.sqlite', '*.db']),
    'gdb': ('File Geodatabase', True, ['*.gdb']),
}


class Urban_research:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor."""
        self.iface = iface
        self.plugin_dir = os.path.dirname(__file__)
        
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'Urban_research_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        self.actions = []
        self.menu = self.tr(u'&Walkability Analysis')
        self.toolbar = self.iface.addToolBar(u'Urban_research')
        self.toolbar.setObjectName(u'Urban_research')

        self.pluginIsActive = False
        self.dlg = None
        self.processing_task = None
        self._active_task = None

        # Граф и данные
        self.graph = {}
        self.node_coords = {}
        self.massive_edge_data = []
        self.edge_data = {}
        self.edge_indices_by_key = defaultdict(list)
        self.edge_spatial_index = None
        self.edge_lookup_by_fid = {}
        self.park_spatial_index = None
        self.park_buffered_by_fid = {}
        self.path_cache = {}
        self.edges_crs = None

        # Логируем версию QGIS
        qgis_version = Qgis.QGIS_VERSION
        self.log(f"✓ Плагин Walkability загружен для QGIS {qgis_version} ({'PyQt6' if IS_QGIS4 else 'PyQt5'})")

    def tr(self, message):
        """Get the translation for a string using Qt translation API."""
        return QCoreApplication.translate('Urban_research', message)

    def add_action(self, icon_path, text, callback, enabled_flag=True,
                   add_to_menu=True, add_to_toolbar=True, status_tip=None,
                   whats_this=None, parent=None):
        """Add a toolbar icon to the toolbar."""
        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)
        if whats_this is not None:
            action.setWhatsThis(whats_this)
        if add_to_toolbar:
            self.toolbar.addAction(action)
        if add_to_menu:
            self.iface.addPluginToMenu(self.menu, action)

        self.actions.append(action)
        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""
        icon_path = os.path.join(self.plugin_dir, 'icon.png')
        self.add_action(
            icon_path,
            text=self.tr(u'Walkability Analysis'),
            callback=self.run,
            parent=self.iface.mainWindow())

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(self.tr(u'&Walkability Analysis'), action)
            self.iface.removeToolBarIcon(action)
        del self.toolbar

    def log(self, message, level=Qgis.Info):
        """Логирование сообщений в QGIS Message Log."""
        # В QGIS 4 уровни логирования могут отличаться
        if IS_QGIS4:
            # Используем Qgis.MessageLevel
            level_mapping = {
                Qgis.Info: Qgis.MessageLevel.Info,
                Qgis.Warning: Qgis.MessageLevel.Warning,
                Qgis.Critical: Qgis.MessageLevel.Critical,
            }
            actual_level = level_mapping.get(level, Qgis.MessageLevel.Info)
        else:
            actual_level = level
        
        QgsMessageLog.logMessage(str(message), 'Walkability', actual_level)

    def update_progress(self, value):
        """Обновление прогресс-бара."""
        if self._active_task is not None:
            self._active_task.setProgress(value)
            return
        if self.dlg:
            self.dlg.progressBar.setValue(value)

    def set_progress(self, value, task=None):
        """Обновление прогресса для UI или фоновой задачи."""
        if task is not None:
            task.setProgress(value)
            return
        self.update_progress(value)

    # ═══════════════════════════════════════════════════════
    #  ПОДДЕРЖКА ФОРМАТОВ
    # ═══════════════════════════════════════════════════════

    def get_file_format(self, file_path):
        """Определение формата файла по расширению."""
        if not file_path:
            return None, None, False
        
        file_lower = file_path.lower()
        
        for format_key, (format_name, is_db, extensions) in SUPPORTED_FORMATS.items():
            for ext in extensions:
                if file_lower.endswith(ext.lstrip('*')):
                    return format_key, format_name, is_db
        
        return None, 'Unknown', False

    def get_file_filter_string(self):
        """Получить строку фильтра для диалога выбора файла."""
        filters = []
        all_extensions = []
        
        for format_key, (format_name, is_db, extensions) in SUPPORTED_FORMATS.items():
            ext_pattern = ' '.join(extensions)
            filters.append(f"{format_name} ({ext_pattern})")
            all_extensions.extend(extensions)
        
        all_ext_pattern = ' '.join(all_extensions)
        filter_str = f"Spatial Data ({all_ext_pattern});;{(';;').join(filters)};;All files (*.*)"
        return filter_str

    def get_format_display_string(self):
        """Получить строку с описанием поддерживаемых форматов."""
        format_list = []
        for format_key, (format_name, is_db, extensions) in SUPPORTED_FORMATS.items():
            ext_str = ', '.join([e.lstrip('*') for e in extensions])
            format_list.append(f"{format_name} ({ext_str})")
        return ', '.join(format_list)

    # ═══════════════════════════════════════════════════════
    #  НАСТРОЙКА ФАЙЛОВОГО ЛОГИРОВАНИЯ
    # ═══════════════════════════════════════════════════════

    def setup_file_logging(self, output_dir):
        """Настройка логирования в файл."""
        log_file = os.path.join(output_dir, "walkability.log")
        for handler in logging.root.handlers[:]:
            logging.root.removeHandler(handler)
        
        logging.basicConfig(
            filename=log_file,
            level=logging.INFO,
            format='%(asctime)s - %(levelname)s - %(message)s',
            datefmt='%Y-%m-%d %H:%M:%S'
        )
        self.log(f"Файл лога: {log_file}")
        logging.info("=== НАЧАЛО СЕАНСА ===")
        logging.info(f"QGIS версия: {Qgis.QGIS_VERSION}")
        logging.info(f"Qt Framework: {'PyQt6' if IS_QGIS4 else 'PyQt5'}")

    # ═══════════════════════════════════════════════════════
    #  ВСПОМОГАТЕЛЬНЫЕ ФУНКЦИИ
    # ═══════════════════════════════════════════════════════

    def safe_weight(self, w, fallback_length=None):
        """Гарантирует положительный конечный вес."""
        try:
            w = float(w)
        except (TypeError, ValueError):
            w = -1.0
        if not math.isfinite(w) or w <= 0:
            return float(fallback_length) if fallback_length and fallback_length > 0 else MIN_WEIGHT
        return w

    def normalized_field_name(self, text):
        """Имя поля из комбобокса."""
        if text is None:
            return None
        s = str(text).strip()
        return s if s else None

    def is_missing_weight_value(self, val):
        """True, если значение атрибута для веса не задано."""
        return check_null_value(val)

    def get_geometry_type_name(self, geom_type):
        """Получить название типа геометрии."""
        # В QGIS 4 геометрические типы могут быть enum'ами
        if IS_QGIS4:
            geom_names = {
                QgsWkbTypes.GeometryType.PointGeometry: "Point",
                QgsWkbTypes.GeometryType.LineGeometry: "LineString",
                QgsWkbTypes.GeometryType.PolygonGeometry: "Polygon",
                QgsWkbTypes.GeometryType.UnknownGeometry: "Unknown",
                QgsWkbTypes.GeometryType.NullGeometry: "Null",
            }
        else:
            geom_names = {
                QgsWkbTypes.PointGeometry: "Point",
                QgsWkbTypes.LineGeometry: "LineString",
                QgsWkbTypes.PolygonGeometry: "Polygon",
                QgsWkbTypes.UnknownGeometry: "Unknown",
                QgsWkbTypes.NullGeometry: "Null",
            }
        return geom_names.get(geom_type, "Unknown")

    def convert_to_point_geometry(self, layer):
        """Конвертирует полигональную геометрию в центроиды."""
        geom_type = layer.geometryType()
        
        # Проверка типа геометрии с учётом версии
        if IS_QGIS4:
            is_point = geom_type == QgsWkbTypes.GeometryType.PointGeometry
        else:
            is_point = geom_type == QgsWkbTypes.PointGeometry
        
        if is_point:
            self.log("Геометрия точечная, конвертация не нужна")
            return layer
        
        self.log("Конвертация полигонов → центроиды...")
        fields = layer.fields()
        point_layer = QgsVectorLayer(f"Point?crs={layer.crs().authid()}", "temp_points", "memory")
        point_layer.dataProvider().addAttributes(fields)
        point_layer.updateFields()
        
        features = []
        for feat in layer.getFeatures():
            geom = feat.geometry()
            if geom and not geom.isEmpty():
                centroid = geom.centroid()
                new_feat = QgsFeature(fields)
                new_feat.setGeometry(centroid)
                new_feat.setAttributes(feat.attributes())
                features.append(new_feat)
        
        point_layer.dataProvider().addFeatures(features)
        self.log(f"Конвертировано: {len(features)} объектов")
        return point_layer

    def load_layer_from_file(self, file_path, layer_name=None):
        """Загрузка слоя из файла с поддержкой множества форматов."""
        if not file_path or file_path == 'NULL':
            self.log(f"Путь к файлу пуст или равен 'NULL'", Qgis.Warning)
            return None
        
        if not os.path.exists(file_path):
            self.log(f"Файл не существует: {file_path}", Qgis.Warning)
            return None
        
        format_key, format_name, is_database = self.get_file_format(file_path)
        
        if format_key is None:
            self.log(f"Неизвестный формат файла: {file_path}\n"
                    f"Поддерживаемые форматы: {self.get_format_display_string()}", 
                    Qgis.Warning)
            return None
        
        provider = "ogr"
        uri = file_path
        
        if is_database and '|' not in file_path:
            temp_layer = QgsVectorLayer(file_path, "", "ogr")
            if not temp_layer.isValid():
                self.log(f"Не удалось открыть {format_name}: {file_path}", Qgis.Warning)
                return None
            
            sub_layers = temp_layer.dataProvider().subLayers()
            if not sub_layers:
                self.log(f"{format_name} не содержит векторных слоёв: {file_path}", Qgis.Warning)
                return None
            
            first_layer_info = sub_layers[0]
            if "!!::!!" in first_layer_info:
                first_layer = first_layer_info.split("!!::!!")[1]
            else:
                first_layer = first_layer_info
            
            uri = f"{file_path}|layername={first_layer}"
            self.log(f"{format_name}: автоматически выбран слой '{first_layer}'")
        
        layer = QgsVectorLayer(uri, layer_name or os.path.basename(file_path), provider)
        if not layer.isValid():
            error_msg = layer.error().message() if hasattr(layer.error(), 'message') else "Unknown error"
            self.log(f"Не удалось загрузить слой: {uri}\nОшибка: {error_msg}", Qgis.Warning)
            return None
        
        feat_count = layer.featureCount()
        if feat_count < 0:
            self.log(f"Слой загружен, но содержит невалидную геометрию: {file_path}", Qgis.Warning)
            return None
        
        if feat_count == 0:
            self.log(f"⚠ Слой загружен, но не содержит объектов: {file_path}", Qgis.Warning)
        
        geom_type_str = self.get_geometry_type_name(layer.geometryType())
        crs_str = layer.crs().authid() if layer.crs().isValid() else "No CRS"
        
        if not layer.crs().isValid():
            self.log(f"⚠ ВНИМАНИЕ: Слой загружен БЕЗ системы координат!", Qgis.Warning)
            logging.warning(f"Слой {os.path.basename(file_path)} загружен без CRS")
        
        self.log(f"✓ {format_name}: {os.path.basename(file_path)}")
        self.log(f"  Объектов: {feat_count}, Тип: {geom_type_str}, CRS: {crs_str}, Полей: {len(layer.fields())}")
        
        logging.info(f"Загружен {format_name}: {os.path.basename(file_path)} "
                    f"({feat_count} объектов, CRS: {crs_str})")
        
        return layer

    def preprocess_layer_for_analysis(self, layer, layer_label="Layer"):
        """
        Подготовка слоя для анализа:
        1) перепроекция в метрическую CRS (EPSG:3857),
        2) округление координат геометрии до COORD_PRECISION знаков.
        """
        if not layer or not layer.isValid():
            return layer

        target_crs = QgsCoordinateReferenceSystem(ANALYSIS_CRS)
        source_crs = layer.crs()
        need_transform = (
            source_crs is not None
            and source_crs.isValid()
            and source_crs.authid() != target_crs.authid()
        )

        transform = None
        if need_transform:
            transform = QgsCoordinateTransform(source_crs, target_crs, QgsProject.instance())
            self.log(f"{layer_label}: перепроекция {source_crs.authid()} → {target_crs.authid()}")
        elif source_crs is None or not source_crs.isValid():
            self.log(
                f"{layer_label}: CRS не определена, слой будет использован как {target_crs.authid()}",
                Qgis.Warning
            )

        wkb_name = QgsWkbTypes.displayString(layer.wkbType())
        prepped_layer = QgsVectorLayer(
            f"{wkb_name}?crs={target_crs.authid()}",
            f"{layer.name()}_prepped",
            "memory"
        )
        provider = prepped_layer.dataProvider()
        provider.addAttributes(layer.fields())
        prepped_layer.updateFields()

        prepared_features = []
        for feat in layer.getFeatures():
            geom = feat.geometry()
            if not geom or geom.isEmpty():
                continue

            geom_copy = QgsGeometry(geom)
            if transform is not None:
                try:
                    geom_copy.transform(transform)
                except Exception as e:
                    self.log(f"{layer_label}: ошибка перепроекции объекта {feat.id()}: {str(e)}", Qgis.Warning)
                    continue

            rounded_geom = QgsGeometry.fromWkt(geom_copy.asWkt(COORD_PRECISION))
            if not rounded_geom or rounded_geom.isEmpty():
                continue

            new_feat = QgsFeature(prepped_layer.fields())
            new_feat.setAttributes(feat.attributes())
            new_feat.setGeometry(rounded_geom)
            prepared_features.append(new_feat)

        provider.addFeatures(prepared_features)
        prepped_layer.updateExtents()
        self.log(
            f"{layer_label}: подготовлено объектов {len(prepared_features)} "
            f"(CRS={target_crs.authid()}, округление={COORD_PRECISION} знака)"
        )
        return prepped_layer

    # ═══════════════════════════════════════════════════════
    #  ПОСТРОЕНИЕ ГРАФА
    # ═══════════════════════════════════════════════════════

    def build_edge_spatial_index(self):
        """Построение spatial index для рёбер графа."""
        self.edge_spatial_index = QgsSpatialIndex()
        self.edge_lookup_by_fid = {}
        fid = 0

        for edge_key in self.edge_data.keys():
            n1, n2 = edge_key
            p1 = self.node_coords[n1]
            p2 = self.node_coords[n2]
            edge_geom = QgsGeometry.fromPolylineXY([p1, p2])

            edge_feat = QgsFeature()
            edge_feat.setId(fid)
            edge_feat.setGeometry(edge_geom)
            self.edge_spatial_index.addFeature(edge_feat)
            self.edge_lookup_by_fid[fid] = edge_key
            fid += 1

        self.log(f"Построен spatial index рёбер: {len(self.edge_lookup_by_fid)}")

    def get_edge_data_by_key(self, edge_key):
        """Получить активные данные ребра по его ключу."""
        idx = self.edge_data.get(edge_key)
        if idx is None:
            return None
        if idx < 0 or idx >= len(self.massive_edge_data):
            return None
        return self.massive_edge_data[idx]

    def calculate_route_length_direct(self, path_nodes):

        if not path_nodes or len(path_nodes) < 2:
            return 0.0
        
        total_length = 0.0
        
        for i in range(len(path_nodes) - 1):
            n1 = path_nodes[i]
            n2 = path_nodes[i + 1]
            
            if n1 not in self.node_coords or n2 not in self.node_coords:
                self.log(f"Предупреждение: узел не найден в node_coords", Qgis.Warning)
                continue
                
            # Получаем координаты в EPSG:3857 (метры)
            p1 = self.node_coords[n1]  # QgsPointXY в EPSG:3857
            p2 = self.node_coords[n2]  # QgsPointXY в EPSG:3857
            
            # Евклидово расстояние в метрах (прямая формула для плоских координат)
            segment_length = math.sqrt((p2.x() - p1.x())**2 + (p2.y() - p1.y())**2)
            total_length += segment_length
        
        # Результат ВСЕГДА в метрах (EPSG:3857)
        return total_length

    def register_edge_data(self, n1, n2, length, weight, template=None):
        """Добавить ребро в massive_edge_data и обновить индексные словари."""
        edge_key = tuple(sorted([n1, n2]))
        edge_data_item = {
            'edge_key': edge_key,
            'n1': n1,
            'n2': n2,
            'length': float(length),
            'time(minutes)': float(length) / 66.667 if float(length) > 0 else 0.0,
            'weight': float(weight),
            'weight_width': 1.0,
            'surface_coeff': 1.0,
            'near_park': False,
            'park_proximity': PARK_PROXIMITY_FAR
        }

        if template:
            for key in ('weight_width', 'surface_coeff', 'near_park', 'park_proximity', 'density_val', 'density_factor'):
                if key in template:
                    edge_data_item[key] = template[key]

        edge_idx = len(self.massive_edge_data)
        self.massive_edge_data.append(edge_data_item)
        self.edge_indices_by_key[edge_key].append(edge_idx)

        best_idx = self.edge_data.get(edge_key)
        if best_idx is None or edge_data_item['weight'] < self.massive_edge_data[best_idx]['weight']:
            self.edge_data[edge_key] = edge_idx
        return edge_idx

    def build_park_spatial_index(self, park_layer):
        """Построение spatial index для буферов парков."""
        self.park_spatial_index = QgsSpatialIndex()
        self.park_buffered_by_fid = {}
        fid = 0

        for feat in park_layer.getFeatures():
            geom = feat.geometry()
            if not geom or geom.isEmpty():
                continue
            buffered = geom.buffer(POLYGON_BUFFER_M, 5)
            if not buffered or buffered.isEmpty():
                continue

            park_feat = QgsFeature()
            park_feat.setId(fid)
            park_feat.setGeometry(buffered)
            self.park_spatial_index.addFeature(park_feat)
            self.park_buffered_by_fid[fid] = buffered
            fid += 1

        self.log(f"Построен spatial index парков: {len(self.park_buffered_by_fid)}")

    def build_graph(self, edges_layer, width_field=None, surface_field=None):
        self.log("\n── Построение графа ──")
        self.update_progress(20)
        
        # Сохраняем CRS слоя 
        self.edges_crs = edges_layer.crs()
        
        # Проверка проекции
        if self.edges_crs.authid() != ANALYSIS_CRS:
            self.log(
                f"⚠️ ВНИМАНИЕ: Слой не в {ANALYSIS_CRS}! "
                f"Текущая CRS: {self.edges_crs.authid()}. "
                f"Расчёт длины может быть неточным!",
                Qgis.Warning
            )
            logging.warning(
                f"Граф строится в CRS {self.edges_crs.authid()}, "
                f"ожидалась {ANALYSIS_CRS}"
            )
        else:
            self.log(f"✓ Слой в метрической CRS: {ANALYSIS_CRS}")
            logging.info(f"Граф строится в {ANALYSIS_CRS} (метры)")
        
        self.graph = defaultdict(dict)
        self.node_coords = {}
        self.massive_edge_data = []
        self.edge_data = {}
        self.edge_indices_by_key = defaultdict(list)
        self.edge_spatial_index = None
        self.edge_lookup_by_fid = {}
        edge_count = 0
        
        for feat in edges_layer.getFeatures():
            geom = feat.geometry()
            if not geom or geom.isEmpty():
                continue
            
            width_val = feat[width_field] if width_field else None
            surface_val = feat[surface_field] if surface_field else None
            
            weight_width = self.calc_width_weight(width_val)
            surface_coeff = self.calc_surface_coeff(surface_val)
            
            if geom.isMultipart():
                lines = geom.asMultiPolyline()
            else:
                lines = [geom.asPolyline()]
            
            for line in lines:
                for i in range(len(line) - 1):
                    p1 = line[i]
                    p2 = line[i + 1]
                    
                    n1 = (round(p1.x(), COORD_PRECISION), round(p1.y(), COORD_PRECISION))
                    n2 = (round(p2.x(), COORD_PRECISION), round(p2.y(), COORD_PRECISION))
                    
                    self.node_coords[n1] = p1
                    self.node_coords[n2] = p2
                    
                    length = math.sqrt((p2.x() - p1.x())**2 + (p2.y() - p1.y())**2)
                    weight = length * weight_width * surface_coeff
                    
                    self.graph[n1][n2] = weight
                    self.graph[n2][n1] = weight
                    
                    self.register_edge_data(
                        n1, n2, length, weight,
                        template={
                            'weight_width': weight_width,
                            'surface_coeff': surface_coeff,
                            'near_park': False,
                            'park_proximity': PARK_PROXIMITY_FAR
                        }
                    )
                    edge_count += 1
        
        self.log(f"Построен граф: {len(self.node_coords)} вершин, {edge_count} рёбер")
        logging.info(f"Построен граф: {len(self.node_coords)} вершин, {edge_count} рёбер")
        self.build_edge_spatial_index()
        return True

    def calc_width_weight(self, width_val):
        """Вычисление коэффициента ширины."""
        if self.is_missing_weight_value(width_val):
            return 1.0
        try:
            w = float(width_val)
            if w > 0:
                return max(1.0 - 1.0 / (WIDTH_SCALE * w), MIN_WEIGHT)
        except (TypeError, ValueError):
            pass
        return 1.0

    def calc_surface_coeff(self, surface_val):
        """Вычисление коэффициента покрытия."""
        if self.is_missing_weight_value(surface_val):
            return 1.0
        surface_str = str(surface_val).strip().lower()
        return SURFACE_COEFFS.get(surface_str, 1.0)

    # Остальные методы идентичны файлу urban_research_compatible.py
    # (применение весов, вставка точек, Dijkstra, экспорт и т.д.)
    # Код продолжается аналогично...

    def apply_density_weights(self, density_layer, density_field):
        """Применение весов плотности к рёбрам."""
        self.log("\n── Применение весов плотности ──")
        self.update_progress(40)
        
        if not density_layer or not density_field:
            self.log("Плотность не задана, пропускаем")
            logging.info("Плотность не задана – веса плотности не применялись")
            return
        
        spatial_index = QgsSpatialIndex(density_layer.getFeatures())
        density_dict = {}
        for feat in density_layer.getFeatures():
            geom = feat.geometry()
            if geom and not geom.isEmpty():
                density_val = feat[density_field]
                if self.is_missing_weight_value(density_val):
                    continue
                try:
                    dv = float(density_val)
                except (TypeError, ValueError):
                    continue
                if dv <= 0 or not math.isfinite(dv):
                    continue
                density_dict[feat.id()] = dv
        
        updated = 0
        for edge_key, edge_idx in self.edge_data.items():
            data = self.massive_edge_data[edge_idx]
            n1, n2 = edge_key
            p1, p2 = self.node_coords[n1], self.node_coords[n2]
            
            mid_x = (p1.x() + p2.x()) / 2
            mid_y = (p1.y() + p2.y()) / 2
            mid_point = QgsPointXY(mid_x, mid_y)
            
            nearest_ids = spatial_index.nearestNeighbor(mid_point, 1)
            if not nearest_ids:
                continue
            nid = nearest_ids[0]
            if nid not in density_dict:
                continue
            density_val = density_dict[nid]
            
            density_factor = 1.0 - DENSITY_THRESHOLD / density_val
            density_factor = abs(density_factor) if density_factor <= 0 else density_factor or MIN_WEIGHT
            
            old_weight = data['weight']
            new_weight = old_weight * density_factor
            data['weight'] = self.safe_weight(new_weight, data['length'])
            data['density_val'] = density_val
            data['density_factor'] = density_factor
            
            self.graph[n1][n2] = data['weight']
            self.graph[n2][n1] = data['weight']
            updated += 1
        
        self.log(f"Обновлено весов плотности: {updated}")
        logging.info(f"Применены веса плотности: обновлено {updated} рёбер")

    def apply_park_proximity(self, park_layer):
        self.log("\n── Применение весов парков ──")
        self.update_progress(50)
        
        if not park_layer:
            self.log("Парки не заданы, пропускаем")
            logging.info("Парки не заданы – веса близости к паркам не применялись")
            return
        
        self.build_park_spatial_index(park_layer)
        if not self.park_buffered_by_fid:
            self.log("Нет валидных парков")
            return
        
        near_count = 0
        for edge_key, edge_idx in self.edge_data.items():
            data = self.massive_edge_data[edge_idx]
            n1, n2 = edge_key
            p1, p2 = self.node_coords[n1], self.node_coords[n2]
            edge_geom = QgsGeometry.fromPolylineXY([p1, p2])
            
            near_park = False
            candidate_ids = self.park_spatial_index.intersects(edge_geom.boundingBox())
            for park_fid in candidate_ids:
                buff_geom = self.park_buffered_by_fid.get(park_fid)
                if buff_geom is None:
                    continue
                if edge_geom.intersects(buff_geom):
                    near_park = True
                    break
            
            if near_park:
                old_weight = data['weight']
                new_weight = old_weight * PARK_PROXIMITY_NEAR
                data['weight'] = self.safe_weight(new_weight, data['length'])
                data['near_park'] = True
                data['park_proximity'] = PARK_PROXIMITY_NEAR
                
                self.graph[n1][n2] = data['weight']
                self.graph[n2][n1] = data['weight']
                near_count += 1
        
        self.log(f"Рёбер вблизи парков: {near_count}")
        logging.info(f"Применены веса парков: {near_count} рёбер вблизи парков")

    def insert_route_points(self, start_layer, end_layer, id_field):
        """Вставка точек маршрута в граф."""
        self.log("\n── Вставка точек маршрута ──")
        self.update_progress(60)
        
        start_points = []
        end_points = []
        
        if start_layer:
            start_layer = self.convert_to_point_geometry(start_layer)
            for feat in start_layer.getFeatures():
                geom = feat.geometry()
                if geom and not geom.isEmpty():
                    point = geom.asPoint()
                    name = feat[id_field] if id_field else f"start_{feat.id()}"
                    node = self.insert_point_to_graph(point, str(name))
                    if node:
                        start_points.append((str(name), node))
        
        if end_layer:
            end_layer = self.convert_to_point_geometry(end_layer)
            for feat in end_layer.getFeatures():
                geom = feat.geometry()
                if geom and not geom.isEmpty():
                    point = geom.asPoint()
                    name = feat[id_field] if id_field else f"end_{feat.id()}"
                    node = self.insert_point_to_graph(point, str(name))
                    if node:
                        end_points.append((str(name), node))
        
        self.log(f"START точек: {len(start_points)}, END точек: {len(end_points)}")
        logging.info(f"Вставлено точек: START – {len(start_points)}, END – {len(end_points)}")
        return start_points, end_points

    def insert_point_to_graph(self, point, name):
        """Вставка одной точки в граф."""
        px, py = point.x(), point.y()
        node = (round(px, COORD_PRECISION), round(py, COORD_PRECISION))
        
        if node in self.node_coords:
            return node
        
        min_dist = float('inf')
        nearest_edge = None
        proj_point = None

        candidate_edge_keys = []
        if self.edge_spatial_index is not None:
            nearest_ids = self.edge_spatial_index.nearestNeighbor(point, 24)
            candidate_edge_keys = [
                self.edge_lookup_by_fid[edge_fid]
                for edge_fid in nearest_ids
                if edge_fid in self.edge_lookup_by_fid
            ]

        if not candidate_edge_keys:
            candidate_edge_keys = list(self.edge_data.keys())

        for edge_key in candidate_edge_keys:
            n1, n2 = edge_key
            p1, p2 = self.node_coords[n1], self.node_coords[n2]
            qx, qy, dist = self.project_point_on_segment(px, py, p1, p2)
            if dist < min_dist:
                min_dist = dist
                nearest_edge = (n1, n2)
                proj_point = (round(qx, COORD_PRECISION), round(qy, COORD_PRECISION))
        
        if nearest_edge is None:
            self.log(f"Не найдено ребро для точки {name}", Qgis.Warning)
            logging.warning(f"Точка {name} не привязана к графу")
            return None
        
        self.node_coords[node] = point
        self.node_coords[proj_point] = QgsPointXY(proj_point[0], proj_point[1])
        
        dist_to_proj = math.sqrt((px - proj_point[0])**2 + (py - proj_point[1])**2)
        self.graph[node][proj_point] = max(dist_to_proj, MIN_WEIGHT)
        self.graph[proj_point][node] = max(dist_to_proj, MIN_WEIGHT)
        self.register_edge_data(node, proj_point, max(dist_to_proj, MIN_WEIGHT), max(dist_to_proj, MIN_WEIGHT))
        
        n1, n2 = nearest_edge
        edge_key = tuple(sorted([n1, n2]))
        
        edge_info = self.get_edge_data_by_key(edge_key)
        if edge_info is not None:
            p1 = self.node_coords[n1]
            p2 = self.node_coords[n2]
            dist1 = math.sqrt((proj_point[0] - p1.x())**2 + (proj_point[1] - p1.y())**2)
            dist2 = math.sqrt((proj_point[0] - p2.x())**2 + (proj_point[1] - p2.y())**2)
            
            total_len = edge_info['length']
            if total_len > 0:
                ratio = edge_info['weight'] / total_len
                weight1 = dist1 * ratio
                weight2 = dist2 * ratio
            else:
                weight1 = dist1
                weight2 = dist2
            
            if n2 in self.graph[n1]:
                del self.graph[n1][n2]
            if n1 in self.graph[n2]:
                del self.graph[n2][n1]
            
            self.graph[n1][proj_point] = max(weight1, MIN_WEIGHT)
            self.graph[proj_point][n1] = max(weight1, MIN_WEIGHT)
            self.graph[proj_point][n2] = max(weight2, MIN_WEIGHT)
            self.graph[n2][proj_point] = max(weight2, MIN_WEIGHT)
            self.register_edge_data(n1, proj_point, max(dist1, MIN_WEIGHT), max(weight1, MIN_WEIGHT), template=edge_info)
            self.register_edge_data(proj_point, n2, max(dist2, MIN_WEIGHT), max(weight2, MIN_WEIGHT), template=edge_info)
        
        return node

    def project_point_on_segment(self, px, py, p1, p2):
        """Проекция точки на отрезок."""
        ax, ay = p1.x(), p1.y()
        bx, by = p2.x(), p2.y()
        abx, aby = bx - ax, by - ay
        ab2 = abx * abx + aby * aby
        if ab2 < 1e-12:
            return ax, ay, math.sqrt((px - ax)**2 + (py - ay)**2)
        t = max(0.0, min(1.0, ((px - ax) * abx + (py - ay) * aby) / ab2))
        qx = ax + t * abx
        qy = ay + t * aby
        dist = math.sqrt((px - qx)**2 + (py - qy)**2)
        return qx, qy, dist

    def dijkstra(self, start_node, end_node, graph=None):
        """Алгоритм Дейкстры для поиска кратчайшего пути."""
        g = graph if graph is not None else self.graph
        if start_node not in g or end_node not in g:
            return None, float('inf')
        
        dist = {start_node: 0.0}
        prev = {}
        pq = [(0.0, 0, start_node)]
        visited = set()
        counter = 0
        
        while pq:
            d_u, _, u = heapq.heappop(pq)
            if u in visited:
                continue
            visited.add(u)
            if u == end_node:
                break
            for v, weight in g[u].items():
                if v in visited:
                    continue
                new_dist = d_u + weight
                if new_dist < dist.get(v, float('inf')):
                    dist[v] = new_dist
                    prev[v] = u
                    counter += 1
                    heapq.heappush(pq, (new_dist, counter, v))
        
        if dist.get(end_node, float('inf')) == float('inf'):
            return None, float('inf')
        
        path = []
        current = end_node
        while current is not None:
            path.append(current)
            current = prev.get(current)
        path.reverse()
        return path, dist[end_node]

    def make_path_cache_key(self, start_node, end_node):
        """Ключ кэша маршрута между двумя узлами."""
        return (start_node, end_node)

    def get_shortest_path_cached(self, start_node, end_node):
        """Получить кратчайший путь из кэша или рассчитать."""
        cache_key = self.make_path_cache_key(start_node, end_node)
        cached = self.path_cache.get(cache_key)
        if cached is not None:
            return cached

        path, weight = self.dijkstra(start_node, end_node)
        self.path_cache[cache_key] = (path, weight)

        if path:
            reverse_key = self.make_path_cache_key(end_node, start_node)
            self.path_cache[reverse_key] = (list(reversed(path)), weight)

        return path, weight

    def calculate_nearest_endpoint_routes(self, start_points, end_points):
        """Расчет кратчайшего пути от каждой начальной точки до ближайшей конечной."""
        self.log("\n── Расчет кратчайших путей до ближайших конечных точек ──")
        self.update_progress(70)
        self.path_cache = {}

        nearest_routes = []
        routes_ok = 0
        routes_fail = 0

        self.log(f"Начальных точек: {len(start_points)}, Конечных точек: {len(end_points)}")
        self.log(f"✓ Все расчёты длины выполняются в {ANALYSIS_CRS} (метры)")
        logging.info(f"Расчет кратчайших путей для {len(start_points)} начальных точек")
        logging.info(f"Система координат для расчёта длины: {ANALYSIS_CRS} (метры)")

        for start_name, start_node in start_points:
            min_weight = float('inf')
            best_end_name = None
            best_end_node = None
            best_path = None

            for end_name, end_node in end_points:
                if start_node == end_node:
                    continue

                path, weight = self.get_shortest_path_cached(start_node, end_node)
                if path is not None and weight < min_weight:
                    min_weight = weight
                    best_end_name = end_name
                    best_end_node = end_node
                    best_path = path

            if best_path is None:
                self.log(f"✗ {start_name}: не найдено доступной конечной точки", Qgis.Warning)
                routes_fail += 1
            else:
                nearest_routes.append({
                    'start_name': start_name,
                    'end_name': best_end_name,
                    'start_node': start_node,
                    'end_node': best_end_node,
                    'path': best_path,
                    'weight': min_weight,
                    'vertices': len(best_path),
                    'is_nearest': True
                })
                routes_ok += 1
                self.log(f"✓ [{routes_ok}] {start_name} → {best_end_name} (ближайшая) вес={min_weight:.4f}")

        self.log(f"\n✅ Успешно: {routes_ok}  |  ✗ Ошибок: {routes_fail}")
        logging.info(f"Рассчитано кратчайших путей: успешно {routes_ok}, ошибок {routes_fail}")
        return nearest_routes

    # Методы экспорта, обработки данных, UI и др. сокращены для краткости
    # Полный код идентичен urban_research_compatible.py
    # (можно скопировать методы экспорта, обработки и UI напрямую)

    def export_results(self, output_dir, start_points, end_points, nearest_routes):
        """Экспорт результатов в GeoJSON."""
        self.log("\n── Экспорт результатов ──")
        self.update_progress(90)
        
        if not output_dir:
            self.log("Папка вывода не указана", Qgis.Warning)
            return
        
        os.makedirs(output_dir, exist_ok=True)
        self.export_points_layer(start_points, output_dir, "start_points.geojson", "start")
        self.export_points_layer(end_points, output_dir, "end_points.geojson", "end")
        self.export_metadata(nearest_routes, output_dir, start_points, end_points)

        if nearest_routes:
            self.export_nearest_routes_layer(nearest_routes, output_dir)
            self.log_nearest_endpoints_analysis(nearest_routes, start_points, end_points)

        self.log(f"✓ Результаты сохранены в: {output_dir}")
        logging.info(f"Результаты экспортированы в {output_dir}")

    def add_result_layers_to_project(self, output_dir):
        """Добавить созданные GeoJSON в дерево слоёв."""
        if not output_dir or not os.path.isdir(output_dir):
            self.log("Добавление в проект: папка результатов недоступна", Qgis.Warning)
            return

        project = QgsProject.instance()
        root = project.layerTreeRoot()
        group = root.insertGroup(0, "Walkability")

        layers_spec = [
            ("nearest_endpoint_routes.geojson", "До ближайшего конца (вес)"),
            ("start_points.geojson", "Начальные точки"),
            ("end_points.geojson", "Конечные точки"),
        ]

        added = 0
        for filename, title in layers_spec:
            path = os.path.join(output_dir, filename)
            if not os.path.isfile(path):
                continue
            layer = QgsVectorLayer(path, title, "ogr")
            if not layer.isValid():
                self.log(f"Не удалось открыть слой: {filename}", Qgis.Warning)
                continue
            project.addMapLayer(layer, False)
            group.insertLayer(0, layer)
            added += 1

        if added:
            self.log(f"✓ В проект добавлено слоёв: {added}")
            logging.info(f"Добавлено слоёв в проект: {added}")

    def export_points_layer(self, points, output_dir, filename, role):
        """Экспорт слоя с точками в WGS84."""
        if not points:
            return
        
        fields = QgsFields()
        fields.append(QgsField("name", get_qvariant_type('String')))
        fields.append(QgsField("role", get_qvariant_type('String')))
        
        output_path = os.path.join(output_dir, filename)
        export_crs = QgsCoordinateReferenceSystem(EXPORT_CRS)
        
        transform = None
        if self.edges_crs and self.edges_crs.isValid():
            if self.edges_crs.authid() != export_crs.authid():
                transform = QgsCoordinateTransform(self.edges_crs, export_crs, QgsProject.instance())
        
        if IS_QGIS4:
            options = QgsVectorFileWriter.SaveVectorOptions()
            options.driverName = "GeoJSON"
            options.fileEncoding = "UTF-8"
            
            writer = QgsVectorFileWriter.create(
                output_path, fields, QgsWkbTypes.Point, export_crs,
                QgsProject.instance().transformContext(), options
            )
            
            if writer.hasError() != QgsVectorFileWriter.NoError:
                self.log(f"Ошибка создания файла", Qgis.Critical)
                return
        else:
            writer = QgsVectorFileWriter(
                output_path, "UTF-8", fields, QgsWkbTypes.Point, export_crs, "GeoJSON"
            )
            
            if writer.hasError():
                self.log(f"Ошибка создания файла", Qgis.Critical)
                return
        
        for name, node in points:
            feat = QgsFeature(fields)
            feat.setAttribute("name", name)
            feat.setAttribute("role", role)
            
            point_geom = QgsGeometry.fromPointXY(self.node_coords[node])
            if transform:
                point_geom.transform(transform)
            
            feat.setGeometry(point_geom)
            writer.addFeature(feat)
        
        del writer
        self.log(f"✓ {filename} ({len(points)} точек)")

    def export_metadata(self, routes, output_dir, start_points, end_points):
        """Экспорт метаданных."""
        metadata = {
            "qgis_version": Qgis.QGIS_VERSION,
            "qt_framework": "PyQt6" if IS_QGIS4 else "PyQt5",
            "routes_calculated": len(routes),
            "start_points": len(start_points),
            "end_points": len(end_points),
            "graph_nodes": len(self.node_coords),
            "graph_edges": sum(len(neighbors) for neighbors in self.graph.values()) // 2,
            
            # Информация о системах координат
            "coordinate_systems": {
                "analysis_crs": ANALYSIS_CRS,
                "analysis_crs_description": "Web Mercator (метры)",
                "export_crs": EXPORT_CRS,
                "export_crs_description": "WGS84 (градусы)",
                "source_crs": self.edges_crs.authid() if self.edges_crs else "Unknown"
            },
            
            # Информация о единицах измерения
            "units": {
                "length": "meters",
                "length_note": "Длина ВСЕГДА в метрах, вычисляется в EPSG:3857",
                "time": "minutes",
                "speed": "4 km/h (66.667 m/min)",
                "coordinates_export": "degrees (WGS84)",
                "coordinates_calculation": "meters (Web Mercator)"
            },
            
            # Формула расчёта
            "calculation": {
                "formula_weight": "weight = length × (1-4000/density) × park_prox × (1-1/(10×width)) × surface_coeff",
                "formula_length": "length = Σ √((x₂-x₁)² + (y₂-y₁)²) в EPSG:3857",
                "formula_time": "time = length / 66.667 (минуты)",
                "density_threshold": DENSITY_THRESHOLD,
                "park_buffer_m": POLYGON_BUFFER_M,
                "park_proximity_near": PARK_PROXIMITY_NEAR,
                "coord_precision": COORD_PRECISION
            }
        }
        output_path = os.path.join(output_dir, "metadata.json")
        with open(output_path, 'w', encoding='utf-8') as f:
            json.dump(metadata, f, ensure_ascii=False, indent=2)
        self.log("✓ metadata.json")

    def export_nearest_routes_layer(self, nearest_routes, output_dir):
        """Экспорт слоя с кратчайшими путями."""
        if not nearest_routes:
            return
        
        fields = QgsFields()
        fields.append(QgsField("start", get_qvariant_type('String')))
        fields.append(QgsField("nearest_end", get_qvariant_type('String')))
        fields.append(QgsField("weight", get_qvariant_type('Double')))
        fields.append(QgsField("length", get_qvariant_type('Double')))
        fields.append(QgsField("time(minutes)", get_qvariant_type('Double')))
        fields.append(QgsField("vertices", get_qvariant_type('Int')))
        
        output_path = os.path.join(output_dir, "nearest_endpoint_routes.geojson")
        export_crs = QgsCoordinateReferenceSystem(EXPORT_CRS)
        
        transform = None
        if self.edges_crs and self.edges_crs.authid() != export_crs.authid():
            transform = QgsCoordinateTransform(self.edges_crs, export_crs, QgsProject.instance())
        
        if IS_QGIS4:
            options = QgsVectorFileWriter.SaveVectorOptions()
            options.driverName = "GeoJSON"
            options.fileEncoding = "UTF-8"
            
            writer = QgsVectorFileWriter.create(
                output_path, fields, QgsWkbTypes.LineString, export_crs,
                QgsProject.instance().transformContext(), options
            )
            
            if writer.hasError() != QgsVectorFileWriter.NoError:
                self.log(f"Ошибка создания файла", Qgis.Critical)
                return
        else:
            writer = QgsVectorFileWriter(
                output_path, "UTF-8", fields, QgsWkbTypes.LineString, export_crs, "GeoJSON"
            )
            
            if writer.hasError():
                self.log(f"Ошибка создания файла", Qgis.Critical)
                return
        
        for route in nearest_routes:
            feat = QgsFeature(fields)
            feat.setAttribute("start", route['start_name'])
            feat.setAttribute("nearest_end", route['end_name'])
            feat.setAttribute("weight", round(route['weight'], 6))
            
            # ВАЖНО: Длина вычисляется в EPSG:3857 (метры)
            # Координаты узлов из self.node_coords всегда в EPSG:3857
            # Результат всегда в метрах, независимо от CRS экспорта
            total_length = self.calculate_route_length_direct(route['path'])
            feat.setAttribute("length", round(total_length, 2))  # МЕТРЫ
            
            # Время: длина_в_метрах / скорость_м_мин (4 км/ч = 66.667 м/мин)
            time_val = total_length / 66.667 if total_length > 0 else 0.0
            feat.setAttribute("time(minutes)", round(time_val, 6))
            feat.setAttribute("vertices", route['vertices'])
            
            points = [self.node_coords[node] for node in route['path']]
            line_geom = QgsGeometry.fromPolylineXY(points)
            
            if transform:
                line_geom.transform(transform)
            
            feat.setGeometry(line_geom)
            writer.addFeature(feat)
        
        del writer
        self.log(f"✓ nearest_endpoint_routes.geojson ({len(nearest_routes)} маршрутов)")

    def log_nearest_endpoints_analysis(self, nearest_routes, start_points, end_points):
        """Логирование аналитического отчета."""
        if not nearest_routes:
            return
        
        endpoint_usage = defaultdict(int)
        weights_list = []
        lengths_list = []
        
        for route in nearest_routes:
            endpoint_usage[route['end_name']] += 1
            weights_list.append(route['weight'])
            total_length = self.calculate_route_length_direct(route['path'])
            lengths_list.append(total_length)
        
        avg_weight = sum(weights_list) / len(weights_list) if weights_list else 0
        avg_length = sum(lengths_list) / len(lengths_list) if lengths_list else 0
        
        logging.info("\n" + "=" * 70)
        logging.info("АНАЛИЗ КРАТЧАЙШИХ ПУТЕЙ")
        logging.info("=" * 70)
        logging.info(f"\nРассчитано маршрутов: {len(nearest_routes)}")
        logging.info(f"Средний вес: {avg_weight:.6f}")
        logging.info(f"Средняя длина: {avg_length:.2f} м")
        
        for idx, route in enumerate(nearest_routes, 1):
            total_length = self.calculate_route_length_direct(route['path'])
            logging.info(f"\nМаршрут #{idx}")
            logging.info(f"  {route['start_name']} → {route['end_name']}")
            logging.info(f"  Длина: {total_length:.2f} м")
        
        logging.info("=" * 70 + "\n")

    def collect_processing_params(self):
        """Сбор параметров из UI."""
        return {
            "edges_path": self.dlg.EDGES_GPKG.filePath(),
            "start_path": self.dlg.FIELD_NAME.filePath(),
            "end_path": self.dlg.END_FILES.filePath(),
            "density_path": self.dlg.WEIGHT_POINTS_GPKG.filePath(),
            "park_path": self.dlg.POLYGON_GPKG.filePath(),
            "output_dir": self.dlg.OUTPUT_DIR.filePath(),
            "width_field": self.normalized_field_name(
                self.dlg.WIDTH_FIELD.currentText() if self.dlg.WIDTH_FIELD.count() > 0 else None),
            "surface_field": self.normalized_field_name(
                self.dlg.SURFACE_FIELD.currentText() if self.dlg.SURFACE_FIELD.count() > 0 else None),
            "id_field": self.normalized_field_name(
                self.dlg.FIELD_NAME_2.currentText() if self.dlg.FIELD_NAME_2.count() > 0 else None),
            "density_field": self.normalized_field_name(
                self.dlg.WEIGHT_FIELD.currentText() if self.dlg.WEIGHT_FIELD.count() > 0 else None),
            "add_layers_to_project": self.dlg.CHECK_ADD_LAYERS_TO_PROJECT.isChecked(),
        }

    def process_data(self, params, task=None):
        """Основная функция обработки данных."""
        start_time = datetime.now()
        try:
            self.log("\n" + "="*60)
            self.log("НАЧАЛО ОБРАБОТКИ")
            self.log("="*60)
            self.set_progress(0, task)
            
            self.setup_file_logging(params["output_dir"])
            
            edges_layer = self.load_layer_from_file(params["edges_path"], "Дорожная сеть")
            if not edges_layer:
                raise Exception("Не удалось загрузить дорожную сеть")
            
            start_layer = self.load_layer_from_file(params["start_path"], "START точки")
            end_layer = self.load_layer_from_file(params["end_path"], "END точки")
            density_layer = self.load_layer_from_file(params["density_path"], "Плотность")
            park_layer = self.load_layer_from_file(params["park_path"], "Парки")

            edges_layer = self.preprocess_layer_for_analysis(edges_layer, "Дорожная сеть")
            if start_layer:
                start_layer = self.preprocess_layer_for_analysis(start_layer, "START точки")
            if end_layer:
                end_layer = self.preprocess_layer_for_analysis(end_layer, "END точки")
            if density_layer:
                density_layer = self.preprocess_layer_for_analysis(density_layer, "Плотность")
            if park_layer:
                park_layer = self.preprocess_layer_for_analysis(park_layer, "Парки")
            
            if not self.build_graph(edges_layer, params["width_field"], params["surface_field"]):
                raise Exception("Ошибка построения графа")
            
            self.apply_density_weights(density_layer, params["density_field"])
            self.apply_park_proximity(park_layer)
            
            start_points, end_points = self.insert_route_points(start_layer, end_layer, params["id_field"])
            if not start_points or not end_points:
                raise Exception("Нет точек для расчёта маршрутов")
            
            nearest_routes = self.calculate_nearest_endpoint_routes(start_points, end_points)

            self.export_results(params["output_dir"], start_points, end_points, nearest_routes)

            if params.get("add_layers_to_project", False):
                self.add_result_layers_to_project(params["output_dir"])
            
            self.set_progress(100, task)
            duration = (datetime.now() - start_time).total_seconds()
            
            self.log("\n" + "="*60)
            self.log("✅ ОБРАБОТКА ЗАВЕРШЕНА УСПЕШНО!")
            self.log("="*60)
            return {
                "routes_count": len(nearest_routes),
                "output_dir": params["output_dir"],
                "duration": duration,
                "layers_added": params.get("add_layers_to_project", False),
            }
        except Exception as e:
            self.log(f"\n❌ ОШИБКА: {str(e)}", Qgis.Critical)
            logging.error(f"КРИТИЧЕСКАЯ ОШИБКА: {str(e)}", exc_info=True)
            self.set_progress(0, task)
            raise

    def _task_process_data(self, task, params):
        """Запуск расчёта внутри фоновой задачи QGIS."""
        self._active_task = task
        try:
            return self.process_data(params, task=task)
        finally:
            self._active_task = None

    def _on_processing_finished(self, exception, result=None):
        """Обработчик завершения фоновой задачи."""
        self.processing_task = None
        if exception is not None:
            QMessageBox.critical(self.dlg, "Ошибка", f"Произошла ошибка:\n\n{str(exception)}")
            self.update_progress(0)
            return
        if not result:
            QMessageBox.warning(self.dlg, "Предупреждение", "Обработка завершена без результата.")
            self.update_progress(0)
            return

        self.update_progress(100)
        msg = (
            f"Обработка завершена!\n\n"
            f"Рассчитано кратчайших маршрутов: {result['routes_count']}\n"
            f"Результаты: {result['output_dir']}\n"
            f"Время: {result['duration']:.2f} сек"
        )
        QMessageBox.information(self.dlg, "Готово", msg)

    def start_processing_task(self):
        """Создать и запустить фоновую задачу обработки."""
        if self.processing_task is not None:
            if self.processing_task.status() in (QgsTask.Queued, QgsTask.Running):
                QMessageBox.information(self.dlg, "Выполняется", "Расчёт уже выполняется.")
                return

        params = self.collect_processing_params()
        self.update_progress(0)
        self.processing_task = QgsTask.fromFunction(
            "Walkability analysis",
            self._task_process_data,
            on_finished=self._on_processing_finished,
            params=params
        )
        QgsApplication.taskManager().addTask(self.processing_task)
        self.log("Фоновая задача запущена")

    def setup_ui_connections(self):
        """Настройка связей UI."""
        self.dlg.REFRESH_SURFACE_WIDTH.clicked.connect(self.update_edges_fields)
        self.dlg.REFRESH_NAME_2.clicked.connect(self.update_identification_fields)
        self.dlg.REFRESH_WEIGHT.clicked.connect(self.update_density_fields)
        
        self.dlg.EDGES_GPKG.fileChanged.connect(self.update_edges_fields)
        self.dlg.FIELD_NAME.fileChanged.connect(self.update_identification_fields)
        self.dlg.END_FILES.fileChanged.connect(self.update_identification_fields)
        self.dlg.WEIGHT_POINTS_GPKG.fileChanged.connect(self.update_density_fields)
        
        # Настройка режима выбора директории
        if QgsFileWidget is not None:
            try:
                # В QGIS 4 может быть другой enum
                if hasattr(QgsFileWidget, 'GetDirectory'):
                    self.dlg.OUTPUT_DIR.setStorageMode(QgsFileWidget.GetDirectory)
                elif hasattr(QgsFileWidget, 'StorageMode'):
                    self.dlg.OUTPUT_DIR.setStorageMode(QgsFileWidget.StorageMode.GetDirectory)
            except Exception as e:
                self.log(f"Предупреждение: не удалось настроить режим выбора папки: {e}", Qgis.Warning)
        
        file_filter = self.get_file_filter_string()
        self.dlg.EDGES_GPKG.setFilter(file_filter)
        self.dlg.FIELD_NAME.setFilter(file_filter)
        self.dlg.END_FILES.setFilter(file_filter)
        self.dlg.WEIGHT_POINTS_GPKG.setFilter(file_filter)
        self.dlg.POLYGON_GPKG.setFilter(file_filter)
        
        self.log(f"✓ Плагин поддерживает форматы: {self.get_format_display_string()}")

    def update_edges_fields(self):
        """Обновление полей для слоя дорог."""
        path = self.dlg.EDGES_GPKG.filePath()
        self.dlg.WIDTH_FIELD.clear()
        self.dlg.SURFACE_FIELD.clear()
        
        if not path:
            return
        
        layer = self.load_layer_from_file(path)
        if layer and layer.isValid():
            field_names = [field.name() for field in layer.fields()]
            self.dlg.WIDTH_FIELD.addItems(field_names)
            self.dlg.SURFACE_FIELD.addItems(field_names)

    def update_identification_fields(self):
        """Обновление поля идентификации."""
        start_path = self.dlg.FIELD_NAME.filePath()
        end_path = self.dlg.END_FILES.filePath()
        path = start_path if start_path else end_path
        
        self.dlg.FIELD_NAME_2.clear()
        
        if not path:
            return
        
        layer = self.load_layer_from_file(path)
        if layer and layer.isValid():
            field_names = [field.name() for field in layer.fields()]
            self.dlg.FIELD_NAME_2.addItems(field_names)

    def update_density_fields(self):
        """Обновление поля плотности."""
        path = self.dlg.WEIGHT_POINTS_GPKG.filePath()
        self.dlg.WEIGHT_FIELD.clear()
        
        if not path:
            return
        
        layer = self.load_layer_from_file(path)
        if layer and layer.isValid():
            field_names = [field.name() for field in layer.fields()]
            self.dlg.WEIGHT_FIELD.addItems(field_names)

    def run(self):
        """Run method that performs all the real work"""
        if self.dlg is None:
            self.dlg = Urban_researchDialog()
            self.setup_ui_connections()
        self.dlg.show()
        
        # В PyQt6 exec_() переименован в exec()
        if IS_QGIS4:
            result = self.dlg.exec()
        else:
            result = self.dlg.exec_()
            
        if result:
            self.start_processing_task()
