# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Urban_researchDialog
                                 A QGIS plugin
 Walkability (QGIS 3 & 4 compatible)
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-04-14
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Student
        email                : a@a.a
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

# ═══════════════════════════════════════════════════════
#  QGIS VERSION DETECTION & COMPATIBILITY LAYER
# ═══════════════════════════════════════════════════════

from qgis.core import Qgis

# Определяем версию QGIS
QGIS_VERSION_INT = Qgis.QGIS_VERSION_INT
IS_QGIS4 = QGIS_VERSION_INT >= 40000

# Условные импорты в зависимости от версии
if IS_QGIS4:
    # QGIS 4.x использует PyQt6
    from PyQt6 import uic
    from PyQt6.QtWidgets import QDialog
else:
    # QGIS 3.x использует PyQt5
    from qgis.PyQt import uic
    from qgis.PyQt.QtWidgets import QDialog

FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'Walkability_dialog_base.ui'))


class Urban_researchDialog(QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(Urban_researchDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
